# General
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
set -g allow-passthrough on
set -g automatic-rename on
set -g renumber-windows on
set -g pane-base-index 1
set -g base-index 1
set -g set-clipboard on
set -g mouse on
set-window-option -g xterm-keys on

# Set C-space as prefix
unbind C-b
set -g prefix C-space
bind C-space send-prefix

# Enable vim mode keys
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection
bind-key -T copy-mode-vi Escape send-keys -X cancel

# Splitting panes with v and h
unbind %
bind h split-window -h
unbind '"'
bind v split-window -v

# Open new panes/windows in current path
bind H split-window -h -c '#{pane_current_path}'
bind V split-window -v -c '#{pane_current_path}'
bind C new-window -c '#{pane_current_path}'

# Switch panes using Alt + arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Switch windows using Shift + <- / ->
bind -n S-Left previous-window 
bind -n S-Right next-window

# Popup
bind-key C-t display-popup -E -w 80% -h 80% ""

# Status bar style
set -g status-position top
set -g status-interval 5
set -g status-left-length 100
set -g status-right-length 100
set -g status-style "fg=black,bg=default"
set -g pane-border-style "fg=black"
set -g pane-active-border-style "fg=blue"
set -g message-style "fg=blue,bg=default"
set -g mode-style "fg=black,bg=blue"
set -g window-status-format "#[fg=black] #I:#W "
set -g window-status-current-format "#[fg=blue,bold] #I:#W "
set -g status-left "#[fg=black,bg=blue] #S #[bg=default] "
set -g status-right "#[fg=blue,bold] #{?client_prefix, ,} #{b:pane_current_path}#(git -C #{pane_current_path} rev-parse --abbrev-ref HEAD 2>/dev/null | sed 's/^/ |  /') | UP #(awk '{print int(\$1/3600)\"h \"int((\$1%3600)/60)\"m\"}' /proc/uptime) "
